---
# code: language=ansible
# Path: ansible/group_vars/all/fluentd.yml
# This file contains the variables for the Fluentd service
fluentd_data_dir_name: svc_fluentd_data
fluentd_data_dir: "{{ docker_volumes_dir }}/{{ fluentd_data_dir_name }}"
fluentd_docker_image_name: grafana/fluent-plugin-loki
fluentd_docker_image_version: main # Fluentd use "edge" instead of "latest"
fluentd_docker_volume_name: svc_fluentd_data_volume
fluentd_ip: 172.16.100.20
