---
# code: language=ansible
# Path: ansible/group_vars/all/postgres.yml
# This file contains the variables for the postgres service

# Postgres Docker image & volume
postgres_docker_image_name: postgres
postgres_docker_image_version: latest
postgres_docker_volume_name: svc_postgres_data_volume
# Postgres Semaphore Data
postgres_semaphore_data_dir_name: svc_postgres_semaphore_data
postgres_semaphore_data_dir: "{{ docker_volumes_dir }}/{{ postgres_semaphore_data_dir_name }}"
# Postgres Vars for the container
