---
# code: language=ansible
# Path: ansible/group_vars/all/vault.yml
# This file contains the variables for the Vault service
vault_volumes_dir_name: svc_vault_data
vault_volumes_dir: "{{ docker_volumes_dir }}/{{ vault_volumes_dir_name }}"

vault_volumes_config_dir_name: svc_vault_config
vault_volumes_config_dir: "{{ docker_volumes_dir }}/{{ vault_volumes_config_dir_name }}"
vault_volumes_logs_dir_name: svc_vault_logs
vault_volumes_logs_dir: "{{ docker_volumes_dir }}/{{ vault_volumes_logs_dir_name }}"
vault_volumes_file_dir_name: svc_vault_file
vault_volumes_file_dir: "{{ docker_volumes_dir }}/{{ vault_volumes_file_dir_name }}"

vault_docker_container_name: svc_vault
vault_docker_ip: "172.16.20.100"
