---
# code: language=ansible
# Path: ansible/roles/svc_vault/tasks/facts/retrieve_seal_state.yml
# This task retrieves the vault seal status

- name: Detect if the vault is sealed # noqa: command-instead-of-shell
  ansible.builtin.shell:
    cmd: "vault status -format=json"
  environment:
    "VAULT_ADDR": "{{ vault_shell_addr }}:{{ vault_shell_port }}"
  register: vault_seal_status
  failed_when: false
  changed_when: false

- name: Set the vault sealed status as a fact
  ansible.builtin.set_fact:
    svc_vault_sealed: !!str "{{ vault_seal_status.stdout | from_json | community.general.json_query('sealed') | bool }}"
