---
# code: language=ansible

- name: Pull traefik image
  community.docker.docker_image_pull:
    name: docker.io/traefik
    tag: latest
    pull: always
    timeout: 10
    tls: true
    tls_hostname: "{{ docker_registry_hostname }}"
  become: true
