---
# code: language=ansible


- name: Include setup_operator_common.yml
  ansible.builtin.include_tasks: setup_operator_common.yml

- name: Include setup_operator_group.yml
  ansible.builtin.include_tasks: setup_operator_group.yml

- name: Include setup_operator_user.yml
  ansible.builtin.include_tasks: setup_operator_users.yml

- name: Import deploy_operator_pgp.yml
  ansible.builtin.import_tasks: deploy_operator_pgp.yml
