---
# code: language=ansible
# Path: ansible/roles/svc_vault/tasks/vault_initialize.yml
# This task initializes the vault and send the unseal keys to the operators


- name: Initialize the vault
  ansible.builtin.shell: # noqa: command-instead-of-shell
    cmd: "vault operator init -key-shares=4 -key-threshold=2 -pgp-keys={{ vault_initialize_pgp_keys }} -non-interactive -format=json"
  environment:
    "VAULT_ADDR": "{{ vault_shell_addr }}:{{ vault_shell_port }}"
  register: vault_init
  changed_when: true

- name: Debug the vault init
  ansible.builtin.debug:
    var: vault_init

# Order of the unseal keys is important and link to the order of the PGP keys in vault_initialize_pgp_keys
- name: Set the vault root token as a fact
  ansible.builtin.set_fact:
    svc_vault_root_token: "{{ vault_init.stdout | from_json | community.general.json_query('root_token') }}"
    svc_vault_unseal_key_0_mirage: "{{ vault_init.stdout | from_json | community.general.json_query('unseal_keys_b64[0]') }}"
    svc_vault_unseal_key_1_nakou: "{{ vault_init.stdout | from_json | community.general.json_query('unseal_keys_b64[1]') }}"
    svc_vault_unseal_key_2_tom: "{{ vault_init.stdout | from_json | community.general.json_query('unseal_keys_b64[2]') }}"
    svc_vault_unseal_key_3_host: "{{ vault_init.stdout | from_json | community.general.json_query('unseal_keys_b64[3]') }}"
    svc_vault_initialized: true

- name: Send the unseal keys to the operators
  community.general.slack:
    token: "{{ slack_token }}"
    channel: "{{ slack_channel }}"
    username: "Ansible - role: svc_vault"
    icon_url: "https://grafana.com/media/solutions/vault-monitor/vault-logo.png"
    blocks:
      - type: header
        text:
          type: plain_text
          text: "Vault Unseal Keys"
      - type: context
        elements:
          - type: "image"
            image_url: "https://grafana.com/media/solutions/vault-monitor/vault-logo.png"
            alt_text: "notifications"
          - type: plain_text
            text: "From {{ ansible_nodename }}/{{ ansible_hostname }} with svc_vault initialization"
      - type: divider
      - type: section
        text:
          type: mrkdwn
          text: "*Unseal Key 0 (Mirage):* ```echo \"{{ svc_vault_unseal_key_0_mirage }}\" | base64 -d | gpg --decrypt```"
      - type: section
        text:
          type: mrkdwn
          text: "*Unseal Key 1 (Nakou):* ```echo \"{{ svc_vault_unseal_key_1_nakou }}\" | base64 -d | gpg --decrypt```"
      - type: section
        text:
          type: mrkdwn
          text: "*Unseal Key 2 (Tom):* ```echo \"{{ svc_vault_unseal_key_2_tom }}\" | base64 -d | gpg --decrypt```"
      - type: section
        text:
          type: mrkdwn
          text: "*Unseal Key 3 (Host):* ```echo \"{{ svc_vault_unseal_key_3_host }}\" | base64 -d | gpg --decrypt```"
