---
# code: language=ansible
# Path: ansible/roles/svc_vault/tasks/vault_initialize.yml
# This task initializes the vault and send the unseal keys to the operators


- name: Initialize the vault
  ansible.builtin.shell: # noqa: command-instead-of-shell
    cmd: "vault operator init -key-shares=3 -key-threshold=2 -pgp-keys={{ vault_initialize_pgp_keys }} -non-interactive -format=json"
  environment:
    "VAULT_ADDR": "{{ vault_shell_addr }}:{{ vault_shell_port }}"
  register: vault_init
  changed_when: true

- name: Debug the vault init
  ansible.builtin.debug:
    var: vault_init

- name: Set the vault root token as a fact
  ansible.builtin.set_fact:
    svc_vault_root_token: "{{ vault_init.stdout | from_json | community.general.json_query('root_token') }}"
    svc_vault_unseal_key_0_mirage: "{{ vault_init.stdout | from_json | community.general.json_query('unseal_keys_b64[0]') }}"
    svc_vault_unseal_key_1_nakou: "{{ vault_init.stdout | from_json | community.general.json_query('unseal_keys_b64[1]') }}"
    svc_vault_unseal_key_2_tom: "{{ vault_init.stdout | from_json | community.general.json_query('unseal_keys_b64[2]') }}"
    svc_vault_initialized: true

- name: Send the unseal keys to the operators
  community.general.slack:
    token: "{{ slack_token }}"
    channel: "{{ slack_channel }}"
    blocks:
      - type: section
        text:
          type: mrkdwn
          text: "*Unseal Key 0 (Mirage):* {{ svc_vault_unseal_key_0_mirage }}"
      - type: section
        text:
          type: mrkdwn
          text: "*Unseal Key 1 (Nakou):* {{ svc_vault_unseal_key_1_nakou }}"
      - type: section
        text:
          type: mrkdwn
          text: "*Unseal Key 2 (Tom):* {{ svc_vault_unseal_key_2_tom }}"
