---
# code: language=ansible
# Path: ansible/roles/deerhide_users/handlers/main.yml
# Handlers

  - name: Import the operator's PGP key # noqa: command-instead-of-shell
    ansible.builtin.shell:
      executable: /bin/bash
      cmd: gpg --import /opt/operator/operator-gpg/keys/*
    become: false
    become_user: "{{ item }}"
    changed_when: false
    with_items: "{{ managed_users }}"
