---
# code: language=ansible
# https://www.sidero.dev/v0.6/getting-started/prereq-kubernetes/

- name: Create dir for indicator file
  ansible.builtin.file:
    path: /opt/sysunicorns/ansible/indicators
    state: directory
    mode: "0755"
    owner: deerhide-operator
    group: deerhide-operator
  become: true

- name: Create dir for talos config
  ansible.builtin.file:
    path: /home/deerhide-operator/.talos/clusters/sysunicorns-sidero
    state: directory
    mode: "0755"
    owner: deerhide-operator
    group: deerhide-operator
  become: true

# Note: we are unable to "configure" the docker network with the "simple" cli, so we are using the default one
# TODO: refactor this to use docker directly instead of the talosctl cluster cli
# https://www.talos.dev/v1.9/talos-guides/install/local-platforms/docker/
- name: Create talos cluster
  ansible.builtin.shell:
    cmd: >
      talosctl cluster create
      --arch amd64
      --provisioner docker
      --name sysunicorns-sidero
      -p 67:67/udp,69:69/udp,8081:8081/tcp,51821:51821/udp,6443:6443/tcp,50000:50000/tcp
      --workers 0
      --config-patch '[{"op": "add", "path": "/cluster/allowSchedulingOnControlPlanes", "value": true}]'
      --endpoint 192.168.60.188
      --docker-host-ip 192.168.60.188
      &>/dev/null
      && sleep 30 &&
      talosctl bootstrap --nodes 192.168.60.188 --endpoints 192.168.60.188 &&
      touch /opt/sysunicorns/ansible/indicators/sidero_cluster_created
  args:
    creates: /opt/sysunicorns/ansible/indicators/sidero_cluster_created

- name: Retrive kubeconfig
  ansible.builtin.shell:
    cmd: >
      talosctl kubeconfig --name sysunicorns-sidero /home/deerhide-operator/.talos/clusters/sysunicorns-sidero/kubeconfig &&
      touch /opt/sysunicorns/ansible/indicators/sidero_cluster_kubeconfig_retrieved
  args:
    creates: /opt/sysunicorns/ansible/indicators/sidero_cluster_kubeconfig_retrieved
