---
# code: language=ansible
- name: Create dir for indicator file
  ansible.builtin.file:
    path: /opt/sysunicorns/sidero
    state: directory
    mode: "0755"
    owner: deerhide-operator
    group: deerhide-operator
  become: true

- name: Create dir for clusterctl config
  ansible.builtin.file:
    path: /home/deerhide-operator/.cluster-api
    state: directory
    mode: "0755"
    owner: deerhide-operator
    group: deerhide-operator
  become: true

- name: Define clusterctl config
  ansible.builtin.template:
    src: clusterctl.yaml.j2
    dest: /home/deerhide-operator/.cluster-api/clusterctl.yaml
    mode: "0644"
    owner: deerhide-operator
    group: deerhide-operator
  become: true

- name: Create namespace sidero-system
  ansible.builtin.command:
    cmd: kubectl create namespace sidero-system && touch /opt/sysunicorns/sidero/sidero_system_namespace_created
  args:
    creates: /opt/sysunicorns/sidero/sidero_system_namespace_created
  failed_when: false
  changed_when: false

- name: Init Sidero
  ansible.builtin.shell:
    cmd: >
      clusterctl init \
        -b talos \
        -c talos \
        -i sidero \
        --target-namespace sidero-system \
        --kubeconfig-context admin@sysunicorns-sidero && \
      touch /opt/sysunicorns/sidero/sidero_in_cluster_initialized
  args:
    creates: /opt/sysunicorns/sidero/sidero_in_cluster_initialized
    executable: /bin/bash
  environment:
    SIDERO_CONTROLLER_MANAGER_HOST_NETWORK: "true"
    SIDERO_CONTROLLER_MANAGER_DEPLOYMENT_STRATEGY: "Recreate"
    SIDERO_CONTROLLER_MANAGER_API_ENDPOINT: "192.168.60.188"
    SIDERO_CONTROLLER_MANAGER_SIDEROLINK_ENDPOINT: "192.168.60.188"
