---
# code: language=ansible

- name: Include requirements.yml
  ansible.builtin.include_tasks: requirements.yml
- name: Include create_kubecluster_in_docker.yml
  ansible.builtin.include_tasks: create_kubecluster_in_docker.yml
- name: Include install_sidero_on_kubecluster.yml
  ansible.builtin.include_tasks: install_sidero_on_kubecluster.yml
- name: Include deploy_manifest.yml
  ansible.builtin.include_tasks: deploy_manifest.yml
