---
# code: language=ansible

- name: Apply network configuration for eth1
  ansible.builtin.copy:
    src: files/02-eth1.yaml
    dest: /etc/netplan/02-eth1.yaml
    mode: '0644'
  become: true
  notify:
    - Apply netplan config
    - Enable eth1
