---
# code: language=ansible
# Path: ansible/roles/svc_postgres/tasks/setup_postgres.yml
# This file contains the tasks to setup the Docker container for Postgres

- name: Pull postgres image
  community.docker.docker_image_pull:
    name: "{{ postgres_docker_image_name }}"
    tag: "{{ postgres_docker_image_version }}"
    pull: always
    timeout: 10
    tls: true
    tls_hostname: "{{ docker_registry_hostname }}"
  become: true

- name: Create directory for postgres
  ansible.builtin.file:
    name: "{{ postgres_data_dir }}"
    state: directory
    mode: "700"
    recurse: true
  become: true

- name: Create docker_volume for postgres data
  community.docker.docker_volume:
    name: "{{ postgres_docker_volume_name }}"
    driver: local
    driver_options:
      type: "none"
      o: "bind"
      device: "{{ postgres_data_dir }}"
    state: present
  become: true

- name: Create a postgres container
  community.docker.docker_container:
    name: svc_postgres
    image: "{{ postgres_docker_image_name }}:{{ postgres_docker_image_version }}"
    state: started
    restart_policy: always
    ports:
      - "5432:5432"
    networks:
      - name: "{{ docker_network_private }}"
    env:
      POSTGRES_USER: "{{ melanie_postgres_root_user }}"
      POSTGRES_PASSWORD: "{{ melanie_postgress_root_password }}"
    volumes:
      - "{{ postgres_data_dir }}:/var/lib/postgresql/data"
    labels:
      traefik.enable: "true"
      traefik.http.routers.svc_postgres.rule: "Host(`postgres.host`)"
      traefik.http.services.svc_postgres.loadbalancer.server.port: "5432"
    recreate: true
  become: true

# - name: Wait for the postgres to be ready
#   ansible.builtin.wait_for:
#     host: "{{ postgres_ip }}"
#     port: 5432
#     state: started
#     delay: 5
#     timeout: 240
