---
# code: language=ansible

- name: Install Python lib for kubernetes
  ansible.builtin.pip:
    name: kubernetes
    state: latest # noqa: package-latest
  become: true
  become_user: "{{ item }}"
  with_items:
    - root
    - deerhide-operator
