---
# code: language=ansible
# [Doc] List of module used
# Copy "https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html"
# Apt "https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html"

- name: Install "unattended-upgrades"
  ansible.builtin.apt:
    name: "unattended-upgrades"
    state: latest # noqa: package-latest
  become: true

- name: Deploy unattended-upgrades config
  ansible.builtin.copy:
    src: files/50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: '0644'
  become: true

- name: Deploy unattended-upgrades schedule config
  ansible.builtin.copy:
    src: files/20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: '0644'
  become: true
