---
- hosts:
  - melanie-dev
  vars:
    ansible_python_interpreter: auto
  roles:
    # This role manage vagrant specificity
    - role: vagrant
    - role: updates
    - role: service_docker
    - role: deerhide_users
