---
# code: language=ansible
- name: Melanie-dev's playbook
  hosts:
    - melanie-dev
  vars:
    ansible_python_interpreter: auto
  roles:
    # This role manage vagrant specificity
    - role: vagrant
    - role: updates
    - role: svc_docker
    - role: svc_traefik
    - role: deerhide_users
