---
# code: language=ansible
# Path: ansible/roles/svc_vault/tasks/setup_docker.yml
# This file contains the tasks to setup the Docker container for Vault
- name: Pull the latest Vault image
  community.docker.docker_image_pull:
    name: hashicorp/vault
    tag: latest
    pull: always
    timeout: 10
    tls: true
    tls_hostname: "{{ docker_registry_hostname }}"
  become: true
  register: docker_image_pull

  # TODO: add a handler to notify through slack if the image was updated (pulled) with the version number
  # TODO: add a handler to restart the container if the image was updated (pulled)

- name: Create docker container for vault
  community.docker.docker_container:
    name: "{{ vault_docker_container_name }}"
    image: hashicorp/vault:latest
    state: started
    restart_policy: always
    volumes:
      - "{{ vault_volumes_file_dir }}:/vault/file"
      - "{{ vault_volumes_config_dir }}:/vault/config"
      - "{{ vault_volumes_logs_dir }}:/vault/logs"
    ipc_mode: "private"
    capabilities:
      - IPC_LOCK
    command: "vault server -config /vault/config/config.json"
    exposed_ports:
      - "8200"
    ports:
      - "127.0.0.1:8200:8200"
    recreate: true
    networks:
      - name: "{{ docker_network_private }}"
        ipv4_address: "{{ vault_docker_ip }}"
    log_driver: "fluentd"
    log_options:
      fluentd-address: "127.0.0.1:24224"
      tag: "svc_vault"
  become: true
