---
# language: ansible
# Path: ansible/roles/svc_vault/tasks/setup_docker_volumes.yml

# Notice : Due to a behavior of the Vault Image, the directories must be created
# but will be always modified by the Vault container with the correct permissions
# and ownership for the Vault user inside the container

# Create directories for Vault volumes
- name: Create a main directory for all Vault Volumes
  ansible.builtin.file:
    name: "{{ vault_volumes_dir }}"
    state: directory
    owner: "deerhide-operator"
    group: "deerhide-operator"
    permissions: "700"
  become: true
  changed_when: false # noqa: ansible-lint See Notice above

- name: Create docker_volume directory for Vault data
  ansible.builtin.file:
    name: "{{ vault_volumes_file_dir }}"
    state: directory
    owner: "deerhide-operator"
    group: "deerhide-operator"
    permissions: "700"
  become: true
  changed_when: false # noqa: ansible-lint See Notice above

- name: Create docker_volume directory for Vault config
  ansible.builtin.file:
    name: "{{ vault_volumes_config_dir }}"
    state: directory
    owner: "deerhide-operator"
    group: "deerhide-operator"
    permissions: "700"
  become: true
  changed_when: false # noqa: ansible-lint See Notice above

- name: Create docker_volume directory for Vault logs
  ansible.builtin.file:
    name: "{{ vault_volumes_logs_dir }}"
    state: directory
    owner: "deerhide-operator"
    group: "deerhide-operator"
    permissions: "700"
  become: true
  changed_when: false # noqa: ansible-lint See Notice above

# Deploy the configuration file for Vault

- name: Deploy the configuration file for Vault
  ansible.builtin.template:
    src: "templates/config.json.j2"
    dest: "{{ vault_volumes_config_dir }}/config.json"
    permissions: "700"
  become: true

# Create docker volumes for Vault

- name: Create docker_volume for Vault data
  community.docker.docker_volume:
    name: "{{ vault_volumes_file_dir_name }}"
    driver: local
    driver_options:
      type: "none"
      o: "bind"
      device: "{{ vault_volumes_file_dir }}"
    state: present
  become: true

- name: Create docker_volume for Vault config
  community.docker.docker_volume:
    name: "{{ vault_volumes_config_dir_name }}"
    driver: local
    driver_options:
      type: "none"
      o: "bind"
      device: "{{ vault_volumes_config_dir }}"
    state: present
  become: true

- name: Create docker_volume for Vault logs
  community.docker.docker_volume:
    name: "{{ vault_volumes_logs_dir_name }}"
    driver: local
    driver_options:
      type: "none"
      o: "bind"
      device: "{{ vault_volumes_logs_dir }}"
    state: present
  become: true
