---
# code: language=ansible
# Path: ansible/roles/svc_minio/tasks/import_gpg_keys.yml
# This file contains the tasks to import and check gpg keys

- name: Import and Check GPG public keys
  block:
    - name: Import GPG Public keys # noqa: command-instead-of-shell
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: gpg --import /opt/operator/operator-gpg/keys/*
      become: false
      become_user: "{{ item }}"
      changed_when: false
      with_items: "{{ managed_users }}"

    - name: Check GPG Public keys # noqa: command-instead-of-shell
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: gpg --list-public-keys --keyid-format=long
      become: false
      become_user: "{{ item }}"
      changed_when: false
      with_items: "{{ managed_users }}"
