---
# code: language=ansible
# Path: ansible/roles/svc_minio/tasks/setup_minio.yml
# This file contains the tasks to setup the Docker container for Minio
- name: Pull minio image
  community.docker.docker_image_pull:
    name: "{{ minio_docker_image_name }}"
    tag: "{{ minio_docker_image_version }}"
    pull: always
    timeout: 10
    tls: true
    tls_hostname: "{{ docker_registry_hostname }}"
  become: true

- name: Create directory for minio
  ansible.builtin.file:
    name: "{{ minio_data_dir }}"
    state: directory
    mode: "700"
    recurse: true
  become: true

- name: Create docker_volume for Minio data
  community.docker.docker_volume:
    name: "{{ minio_docker_volume_name }}"
    driver: local
    driver_options:
      type: "none"
      o: "bind"
      device: "{{ minio_data_dir }}"
    state: present
  become: true

- name: Create a Minio container
  community.docker.docker_container:
    name: svc_minio
    image: "{{ minio_docker_image_name }}:{{ minio_docker_image_version }}"
    state: started
    restart_policy: always
    command: server /data --console-address ":9001"
    exposed_ports:
      - 9000
      - 9001
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    networks:
      - name: "{{ docker_network_private }}"
        ipv4_address: "{{ minio_ip }}"
    env:
      MINIO_ROOT_USER: "{{ melanie_minio_root_user }}"
      MINIO_ROOT_PASSWORD: "{{ melanie_minio_root_password }}"
    volumes:
      - "{{ minio_data_dir }}:/data"
    recreate: true
    log_driver: "fluentd"
    log_options:
      fluentd-address: "127.0.0.1:24224"
      tag: "svc_minio"
  become: true
