---
# code: language=ansible
# [Doc] List of all modules used

- name: Create directory for docker volumes
  ansible.builtin.file:
    path: "{{ docker_volumes_dir }}"
    state: directory
    mode: '0755'
  become: true
